services:
  alist:
    container_name: xiaoya-alist
    image: ghcr.nju.edu.cn/monlor/xiaoya-alist:latest
    volumes:
      - /docker/data/xiaoya:/data
      - /docker/data/xiaoya/opt:/opt/alist/data
    ports:
      - "5678:5678"
      - "2345:2345"
      - "2346:2346"
    env_file:
      - env
    restart: unless-stopped
    networks:
      - default
  metadata:
    container_name: xiaoya-metadata
    image: ghcr.nju.edu.cn/monlor/xiaoya-metadata:latest
    env_file:
      - env
    volumes:
      - /docker/data/emby/cache:/media/config/cache
      - /nasdata/media/downloads/xiaoya/meta:/media/temp
      - /nasdata/media/links/xiaoya:/media/xiaoya
      - /docker/data/xiaoya:/etc/xiaoya
      - /docker/data/emby/config:/media/config
    depends_on:
      - alist
    restart: unless-stopped
    networks:
      - default
  emby:
    container_name: xiaoya-emby
    image: ghcr.nju.edu.cn/monlor/xiaoya-embyserver:latest
    env_file:
      - env
    depends_on:
      - metadata
      - alist
    volumes:
      - /nasdata/media/links/xiaoya:/media
      - /docker/data/emby/config:/config
      - /docker/data/emby/cache:/cache
    ports:
      - "6908:6908"
    restart: unless-stopped
    networks:
      - default

networks:
  default:

volumes:
  xiaoya:
  media:
  config:
  meta:
  cache:
